### ISSUE TITLE
Add CSS styling

### ISSUE THREAD

**Issue by JamesDrysdale** [JamesDrysdale/Naughts_And_Crosses#4]
Enlarge game board and center it on-screen horizontally and vertically.

**Comment by chauhanparth210** [comment]
Hi @JamesDrysdale , I am Parth. I want to work on this issue if you don't mind will you please assign this issue to me and I also wanted to work on the other issues too. Thank you @JamesDrysdale

**Comment by JamesDrysdale** [comment]
> Hi @JamesDrysdale , I am Parth. I want to work on this issue if you don't mind will you please assign this issue to me and I also wanted to work on the other issues too. Thank you @JamesDrysdale

Thank you very much for volunteering Parth. I have assigned this issue to you, and will so the same with the other ones.

**Comment by JamesDrysdale** [comment]
The alignment on this is much better, so thank you for that @chauhanparth210  I'd like the naughts and crosses board to be larger, maybe twice as big as it is by default just now so you can see it easier.

**Comment by chauhanparth210** [comment]
Hey @JamesDrysdale ! thank you dude for accepting my PR. I have some suggestion if you allow me to do that I would love to do it.
-  If I could break down the index.js and make a component wise folder structure like other standard react folder structure.
- I also considering above changes that you  suggested to do that.
- If your wish shell we move to functional base component(react-hooks). 

@JamesDrysdale, if you allowing me to do that. Please give a feedback so i work upon that issues. Thank you @JamesDrysdale .

**Comment by JamesDrysdale** [comment]
> Hey @JamesDrysdale ! thank you dude for accepting my PR. I have some suggestion if you allow me to do that I would love to do it.
> 
> * If I could break down the index.js and make a component wise folder structure like other standard react folder structure.
> * I also considering above changes that you  suggested to do that.
> * If your wish shell we move to functional base component(react-hooks).
> 
> @JamesDrysdale, if you allowing me to do that. Please give a feedback so i work upon that issues. Thank you @JamesDrysdale .

That's a great suggestion and I would be happy for you to make those changes. Thanks!

**Comment by JamesDrysdale** [comment]
I'm going to close this issue now as the primary objective - enlarging the game board, centering it has been met. Thank you @chauhanparth210  for all the work you've done so far to improve this project. I'm very grateful.
