### ISSUE TITLE
Adjust text using CSS

### ISSUE THREAD

**Issue by JamesDrysdale** [JamesDrysdale/Naughts_And_Crosses#5]
Enlarge 'Next Player/Winner' text to make it easier to read and align it above the game board.

**Comment by chauhanparth210** [comment]
Hi @JamesDrysdale, I want to work on this issue will you please assign this issue to me. Thank you @JamesDrysdale

**Comment by chauhanparth210** [comment]
Hi @JamesDrysdale, thank you so much for reviewing  and merging my PR. Is there anything which I had left with this issue ?? because issue is still open .

**Comment by JamesDrysdale** [comment]
You did well @chauhanparth210 I just forgot to click the button to close the issue. Thanks for bringing it to my attention. :)
